spring:
  security:
    enabled: false

h2:
  console:
    enabled: true
    path: /h2-console

datasource:
  url: "jdbc:h2:mem:auth;DB_CLOSE_ON_EXIT=FALSE"
  username: a
  password: a
  driverClassName: org.h2.Driver

jpa:
  database-platform: org.hibernate.dialect.H2Dialect
